[package]
name = "chemical-engine"
version = "0.1.0"
edition = "2024"

[features]
chemical-gui = ["dep:chemical-gui"]
chemical-scripting = ["dep:chemical-scripting"]

[dependencies]
env_logger = "0.10"
log = "0.4"
anyhow = "1.0"
winit = { version = "0.30", features = ["android-native-activity"] }
# Needs to match the wgpu version in iced wgpu
wgpu = "27.0.1"

pollster = "0.3"
bytemuck = { version = "1.24", features = ["derive"] }
glam = { version = "0.33", features = [ "bytemuck", "debug-glam-assert", "fast-math" ] }

chemical-api = { path = "../chemical-api", features = ["dev-api"] }
chemical-gui = { path = "../chemical-gui", optional = true}
chemical-scripting = { path = "../chemical-scripting", optional = true }

[[bin]]
name = "ChemicalGUI"
path = "src/main.rs"
required-features = ["chemical-gui"]

[[bin]]
name = "ChemicalGame"
path = "src/main.rs"
required-features = ["chemical-scripting"]

[lints.rust]
dead_code = "allow"
unused_code = "allow"
