[package]
name = "chemical-gui"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
glam = { version = "0.33", features = [ "bytemuck", "debug-glam-assert", "fast-math" ] }
log = "0.4"
anyhow = "1.0"

iced_wgpu = "0.14.0"
iced_winit = "0.14.0"
iced_widget = { version = "0.14.0", features = ["wgpu"] }

chemical-api = { path = "../chemical-api", features = ["dev-api"] }

[lints.rust]
dead_code = "allow"
unused_code = "allow"
inactive_code = "allow"
