[package]
name = "chemical-scripting"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
glam = { version = "0.33", features = [ "bytemuck", "debug-glam-assert", "fast-math" ] }
log = "0.4"
anyhow = "1.0"
chemical-api = { path = "../chemical-api" }

[lints.rust]
dead_code = "allow"
