[package]
name = "chemical-wgpu"
version = "0.1.2"
edition = "2024"

[features]
chemical-gui = ["dep:chemical-gui"]
chemical-scripting = ["chemical-scripting-integrator/chemical-scripting"]

[dependencies]
anyhow = "1.0"
winit = { version = "0.30", features = ["android-native-activity"] }
env_logger = "0.10"
log = "0.4"
wgpu = "28.0"
pollster = "0.3"
bytemuck = { version = "1.24", features = ["derive"] }
glam = { version = "0.33", features = [ "bytemuck", "debug-glam-assert", "fast-math" ] }
chemical-engine = { path = "../chemical-engine" }
chemical-gui = { path = "../chemical-gui", optional = true}
chemical-scripting-integrator = { path = "../chemical-scripting-integrator" }

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]

[[bin]]
name = "ChemicalEngineGUI"
path = "src/main.rs"
required-features = ["chemical-gui"]

[[bin]]
name = "ProjectGamma"
path = "src/main.rs"
required-features = ["chemical-scripting"]